// Generated by opencli-mcp tools.define on 2026-10-09T10:19:54.128Z
import { defineAdapter } from 'opencli-mcp/adapter-sdk';

export default defineAdapter({
  description: "Read any web page: open the URL and return its main text as plain text (uses your logged-in Chrome session).",
  access: "read",
  domain: "any",
  args: [
    {
      "name": "url",
      "type": "string",
      "required": true,
      "description": "http(s) URL"
    },
    {
      "name": "wait",
      "type": "number",
      "description": "seconds to wait for rendering (default 2)"
    },
    {
      "name": "selector",
      "type": "string",
      "description": "optional CSS selector to scope the text"
    }
  ],
  run: async ({tab, args}) => {
    const waitSec = Math.min(30, Math.max(1, Number(args.wait) || 2));
    await tab.goto(args.url);
    await new Promise(r => setTimeout(r, waitSec * 1000));
    const raw = await tab.evaluate("(" + (function(sel){
      var root = sel ? document.querySelector(sel) : (document.querySelector('main') || document.querySelector('article') || document.body);
      if (!root) return null;
      var c = root.cloneNode(true);
      c.querySelectorAll('script,style,nav,header,footer,aside,iframe,form,button').forEach(function(e){e.remove();});
      var t = (c.innerText || '').replace(/\n{3,}/g, '\n\n').trim();
      return JSON.stringify({title: document.title, text: t.slice(0, 60000)});
    }).toString() + ")(" + JSON.stringify(args.selector || null) + ")");
    const p = JSON.parse(raw);
    return {title: p.title, url: args.url, chars: p.text.length, text: p.text.slice(0, 3000)};
  },
});
